### ISSUE TITLE
Error - Unsupported URL

### ISSUE THREAD

**Issue by scottyedmonds** [Baggette/cbc-gem-downloader#4]
Getting this Error:

` line 955, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://gem.cbc.ca/canadas-ultimate-challenge/s01?autoplay=1`

**Comment by cagenuts** [comment]
CBC/GEM have changed things recently. You now need to filter for m3u8 and use that as the URL. Unfortunately I haven't figured out a way to automatically add metadata and episode images (thumbnails) like it used to be. So that's a manual process via ffmpeg for now.

**Comment by Baggette** [comment]
> Getting this Error:
> 
> ` line 955, in trouble raise DownloadError(message, exc_info) yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://gem.cbc.ca/canadas-ultimate-challenge/s01?autoplay=1`

Yeah im aware of the issue, Im not exactly sure how to fix it though

**Comment by Baggette** [comment]
> CBC/GEM have changed things recently. You now need to filter for m3u8 and use that as the URL. Unfortunately I haven't figured out a way to automatically add metadata and episode images (thumbnails) like it used to be. So that's a manual process via ffmpeg for now.

you can use the old url scheme which is gem.cbc.ca/media/showname/s01e01

**Comment by cagenuts** [comment]
> > CBC/GEM have changed things recently. You now need to filter for m3u8 and use that as the URL. Unfortunately I haven't figured out a way to automatically add metadata and episode images (thumbnails) like it used to be. So that's a manual process via ffmpeg for now.
> 
> you can use the old url scheme which is gem.cbc.ca/media/showname/s01e01

Brilliant thanks.

**Comment by Baggette** [comment]
> > > CBC/GEM have changed things recently. You now need to filter for m3u8 and use that as the URL. Unfortunately I haven't figured out a way to automatically add metadata and episode images (thumbnails) like it used to be. So that's a manual process via ffmpeg for now.
> > 
> > 
> > you can use the old url scheme which is gem.cbc.ca/media/showname/s01e01
> 
> Brilliant thanks.

no problem. Ill try and see if theres a way to fix this issue

**Comment by Baggette** [comment]
bruh they changed more stuff involving authentication, its no longer able to log in 😭

**Comment by Baggette** [comment]
yt-dlp was updated and this issue is solved, it appears that it may require cookies from a browser to download certain content however I cannot tell if this is true or not. the url scheme has changed and its https://gem.cbc.ca/showname/s01e01
